main: pl.ibcgames.smvotifier.Votifier
name: SM-Votifier
authors: [kaziu687, kisi69]
website: https://serwery-minecraft.pl
version: @version@
commands:
  sm-nagroda:
    description: Odbierz nagrode za glosowanie na serwery-minecraft.pl
    usage: /sm-nagroda
  sm-glosuj:
    description: Pokaz adres strony do glosowania
    usage: /sm-glosuj